name: Reset Submission File

on:
  pull_request_target:
    types: [ closed ]
    branches:
      - main

jobs:
  reset:
    name: Reset the submission file to blank after pull-request merge
    # This job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Clear Submit
        run: echo "" > submission.yaml

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'submission.yaml'

