name: Update Website

on:
  # Placeholders for Automated workflow
  #push:
  #  branches:
  #  - main
  #  paths:
  #  - 'indication_paths.yaml'
  workflow_dispatch:  # Allow manual launch on click

jobs:
  # This will synchorinize main to the gh-pages branch
  # Not sure if it would remove `pages` and `images` folders if removed from main
  
  #synchronize:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Merge main to gh-pages branch
  #      uses: devmasx/merge-branch@v1.3.1
  #      with:
  #        type: now
  #        from_branch: main
  #        target_branch: gh-pages
  #        github_token: ${{ github.token }}

  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        #ref: gh-pages # Uncomment to perform this on the gh-pages branch
        token: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Webstie
      run: |
        python parse.py


    - name: Commit latest build
      if: ${{ success() }}
      uses: EndBug/add-and-commit@v7
      with:
        #branch: gh-pages # Un-comment to perform on the gh-pages pranch
        message: "Update to Website"
        add: "['pages', 'images', '_data']"
